# Generated by Django 5.2.7 on 2026-02-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='code',
            field=models.CharField(blank=True, help_text='Optional code (e.g., U-01)', max_length=50, null=True),
        ),
    ]
