# Generated by Django 5.2.7 on 2026-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_flashcard_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='course_mode',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('surgery', 'Surgery'), ('commed', 'Community Medicine')], default='commed', help_text='Course mode for this flashcard set', max_length=20),
        ),
    ]
