# Generated by Django 5.2.7 on 2026-02-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcardset_course_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardset',
            name='course_mode',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('surgery', 'Surgery'), ('commed', 'Community Medicine')], max_length=20),
        ),
    ]
