# Generated by Django 5.2.7 on 2026-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_subscription',
            field=models.BooleanField(default=False, help_text='User has an active subscription'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
