# Generated by Django 5.2.7 on 2026-01-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_has_subscription_user_subscription_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_subscription',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_expiry',
        ),
        migrations.AlterField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text="User's preference for dark mode interface"),
        ),
    ]
