# Generated by Django 5.2.7 on 2026-02-07 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_has_subscription_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('seen', models.BooleanField(default=False)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('answered_correctly', models.BooleanField(default=False, null=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('flipped', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type', 'object_id'], name='accounts_us_user_id_a5c1b5_idx'), models.Index(fields=['user', 'seen'], name='accounts_us_user_id_e2ed72_idx'), models.Index(fields=['user', 'content_type', 'seen'], name='accounts_us_user_id_1d97cd_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
