# Generated by Django 5.2.7 on 2026-02-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userresourceprogress'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userresourceprogress',
            name='accounts_us_user_id_a5c1b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='userresourceprogress',
            name='accounts_us_user_id_e2ed72_idx',
        ),
        migrations.RemoveIndex(
            model_name='userresourceprogress',
            name='accounts_us_user_id_1d97cd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userresourceprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userresourceprogress',
            name='answered_correctly',
        ),
        migrations.RemoveField(
            model_name='userresourceprogress',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userresourceprogress',
            name='flipped',
        ),
        migrations.RemoveField(
            model_name='userresourceprogress',
            name='last_interaction',
        ),
        migrations.RemoveField(
            model_name='userresourceprogress',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='userresourceprogress',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='userresourceprogress',
            name='seen_at',
        ),
        migrations.RemoveField(
            model_name='userresourceprogress',
            name='user',
        ),
    ]
