# Generated by Django 5.2.7 on 2026-02-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userresourceprogress_accounts_us_user_id_a5c1b5_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResourceProgress',
        ),
    ]
