# Generated by Django 5.2.7 on 2026-02-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprogress_usersetattempt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersetattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersetattempt',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='usersetattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
        migrations.DeleteModel(
            name='UserSetAttempt',
        ),
    ]
