# Generated by Django 5.2.7 on 2026-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_usersetattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
