# Generated by Django 5.2.7 on 2026-02-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userresourceprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResourceProgress',
        ),
    ]
