# Generated by Django 5.2.7 on 2026-02-08 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_usersetprogress'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Set Attempt',
                'verbose_name_plural': 'User Set Attempts',
            },
        ),
        migrations.DeleteModel(
            name='UserSetProgress',
        ),
        migrations.AddIndex(
            model_name='usersetattempt',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='accounts_us_user_id_6f9574_idx'),
        ),
        migrations.AddIndex(
            model_name='usersetattempt',
            index=models.Index(fields=['last_attempted'], name='accounts_us_last_at_b7745f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersetattempt',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
