# Generated by Django 5.2.7 on 2026-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_usersetattempt_delete_usersetprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_mode',
            field=models.CharField(blank=True, choices=[('medicine', 'Medicine'), ('surgery', 'Surgery'), ('commed', 'Community Medicine')], help_text="User's selected course mode for content filtering", max_length=20, null=True),
        ),
    ]
