# Generated by Django 5.2.7 on 2026-02-27 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_course_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersetattempt',
            options={},
        ),
        migrations.CreateModel(
            name='FreeTrialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_access', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Free Trial Usage',
                'verbose_name_plural': 'Free Trial Usages',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
