# Generated by Django 5.2.7 on 2026-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_usersetattempt_options_freetrialusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
