# Generated by Django 5.2.7 on 2026-03-14 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_current_session_id'),
        ('osces', '0012_alter_osceset_course_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_osce_set',
            field=models.ForeignKey(blank=True, help_text='The first OSCE set the user accessed for free (one‑set limit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_first_osce', to='osces.osceset'),
        ),
    ]
