# Generated by Django 5.2.7 on 2026-03-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_first_osce_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_osce_set',
        ),
    ]
