# Generated by Django 5.2.7 on 2026-02-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('monthly 2', '2 Month'), ('monthly', '1 Month'), ('three_months', '3 Months'), ('six_months', '6 Months'), ('yearly', '1 Year')], max_length=20, unique=True),
        ),
    ]
