# Generated by Django 5.2.7 on 2026-02-12 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcqs', '0011_add_topic_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.PositiveIntegerField(help_text='Number of questions to include in the contest (randomly selected from the set)')),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('end_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('prize_description', models.TextField(blank=True, help_text='Describe prizes for winners')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mcq_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contests', to='mcqs.mcqset')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('selected_question_ids', models.JSONField(default=list, help_text='List of MCQ IDs selected for this participation')),
                ('answers', models.JSONField(default=dict, help_text='Mapping of question_id -> selected_option_key')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
