# Generated by Django 5.2.7 on 2026-02-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='selected_question_ids',
            field=models.JSONField(blank=True, default=list, help_text='Pre‑selected MCQ IDs for this contest (all users get the same set).'),
        ),
    ]
