# Generated by Django 5.2.7 on 2026-02-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_add_selected_question_ids_to_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='questions_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the full question data (question text, options, explanation).'),
        ),
    ]
