# Generated by Django 5.2.7 on 2026-02-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_questions_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestparticipation',
            name='answers',
            field=models.JSONField(default=dict, help_text="Mapping of question_id -> {option_key: 'T'/'F'/null}"),
        ),
    ]
