# Generated by Django 5.2.7 on 2026-02-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_contestparticipation_answers'),
        ('mcqs', '0015_alter_mcq_mcq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='mcq_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='mcqs.mcqset'),
        ),
    ]
