# Generated by Django 5.2.7 on 2025-11-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oscecard',
            name='image',
            field=models.URLField(blank=True, help_text='URL of the image', null=True),
        ),
    ]
