# Generated by Django 5.2.7 on 2025-11-15 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osces', '0002_alter_oscecard_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='osceset',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_osce_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oscecard',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oscecard',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
