# Generated by Django 5.2.7 on 2026-02-11 07:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osces', '0003_osceset_likes_alter_oscecard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscecard',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
