# Generated by Django 5.2.7 on 2026-02-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osces', '0004_oscecard_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oscecard',
            name='explanation',
        ),
    ]
