# Generated by Django 5.2.7 on 2026-02-11 08:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osces', '0005_remove_oscecard_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='oscecard',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
