# Generated by Django 5.2.7 on 2026-02-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osces', '0006_oscecard_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osceanswer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oscecard',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
