# Generated by Django 5.2.7 on 2026-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osces', '0008_alter_osceanswer_text_alter_oscecard_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osceanswer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oscecard',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
