# Generated by Django 5.2.7 on 2026-02-11 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osces', '0009_alter_osceanswer_text_alter_oscecard_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osceanswer',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='oscecard',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
