# Generated by Django 5.2.7 on 2026-02-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author',
            new_name='user',
        ),
    ]
