# Generated by Django 5.2.7 on 2026-01-31 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0003_mcqset_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_key', models.CharField(blank=True, max_length=5, null=True)),
                ('selected_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('has_seen', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted_at', models.DateTimeField(auto_now=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('correct_on_first_attempt', models.BooleanField(default=False)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='mcqs.mcq')),
                ('mcq_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_history', to='mcqs.mcqset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_attempted_at'],
                'indexes': [models.Index(fields=['user', 'mcq_set', 'is_correct'], name='mcqs_useran_user_id_236870_idx'), models.Index(fields=['user', 'mcq_set', 'has_seen'], name='mcqs_useran_user_id_babe2c_idx')],
                'unique_together': {('user', 'mcq')},
            },
        ),
    ]
