# Generated by Django 5.2.7 on 2026-01-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0004_useranswerhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAnswerHistory',
        ),
    ]
