# Generated by Django 5.2.7 on 2026-02-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0006_usermcqattempt_usermcqprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermcqprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='mcq',
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMCQAttempt',
        ),
        migrations.DeleteModel(
            name='UserMCQProgress',
        ),
    ]
