# Generated by Django 5.2.7 on 2026-02-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0008_usermcqattempt_usermcqprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermcqattempt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermcqprogress',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='usermcqprogress',
            name='unique_user_mcq_progress',
        ),
        migrations.RemoveField(
            model_name='usermcqattempt',
            name='attempted_at',
        ),
        migrations.RemoveField(
            model_name='usermcqattempt',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='usermcqattempt',
            name='mcq',
        ),
        migrations.RemoveField(
            model_name='usermcqattempt',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='usermcqattempt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='correct_attempts',
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='last_attempted',
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='last_is_correct',
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='mcq',
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='usermcqprogress',
            name='user',
        ),
    ]
