# Generated by Django 5.2.7 on 2026-02-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0009_alter_usermcqattempt_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMCQAttempt',
        ),
        migrations.DeleteModel(
            name='UserMCQProgress',
        ),
    ]
