# Generated by Django 5.2.7 on 2026-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0010_delete_usermcqattempt_delete_usermcqprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='topic',
            field=models.CharField(blank=True, help_text='Topic or category (e.g., Epidemiology, Communicable Diseases)', max_length=255, null=True),
        ),
    ]
