# Generated by Django 5.2.7 on 2026-02-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0011_add_topic_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcqset',
            options={'ordering': ['title']},
        ),
    ]
