# Generated by Django 5.2.7 on 2026-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0012_alter_mcqset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqset',
            name='course_mode',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('surgery', 'Surgery'), ('commed', 'Community Medicine')], default='commed', help_text='Course mode for this MCQ set', max_length=20),
        ),
    ]
