# Generated by Django 5.2.7 on 2026-02-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0014_alter_mcqset_course_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='mcq_type',
            field=models.CharField(choices=[('TF', 'True/False'), ('MCQ', 'Multiple Choice')], max_length=10),
        ),
    ]
