# Generated by Django 5.2.7 on 2026-07-21 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db import migrations, models
import hashlib
import json

def populate_fingerprints(apps, schema_editor):
    MCQ = apps.get_model('mcqs', 'MCQ')
    Option = apps.get_model('mcqs', 'Option')
    for mcq in MCQ.objects.all():
        options = Option.objects.filter(mcq=mcq).order_by('key')
        options_data = []
        for opt in options:
            options_data.append({
                'key': opt.key,
                'text': opt.text,
                'is_correct': opt.is_correct,
            })
        data = {
            'question': mcq.question,
            'mcq_type': mcq.mcq_type,
            'options': options_data,
        }
        json_str = json.dumps(data, sort_keys=True, ensure_ascii=False)
        mcq.fingerprint = hashlib.sha256(json_str.encode('utf-8')).hexdigest()
        mcq.save(update_fields=['fingerprint'])


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0015_alter_mcq_mcq_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name='ReportedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user_satisfied', models.BooleanField(blank=True, null=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mcqs.mcq')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mcq', 'user')},
            },
        ),
    ]
