# Generated by Django 5.2.7 on 2026-07-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0016_add_fingerprint_and_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedquestion',
            name='snapshot',
            field=models.JSONField(default=dict, editable=False, help_text='Snapshot of the question in upload JSON format at report time.'),
        ),
    ]
