# Generated by Django 5.2.7 on 2026-07-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0017_reportedquestion_snapshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportedquestion',
            unique_together=set(),
        ),
    ]
