# Generated by Django 5.2.7 on 2026-07-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqs', '0018_alter_reportedquestion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedquestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
