# Generated by Django 5.2.7 on 2026-01-24 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('flashcard_set', 'Flashcard Set'), ('mcq_set', 'MCQ Set'), ('osce_set', 'OSCE Set'), ('note', 'Note')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feed_feedit_created_d2e023_idx'), models.Index(fields=['-score', '-created_at'], name='feed_feedit_score_2ec6b7_idx'), models.Index(fields=['content_type', 'content_id'], name='feed_feedit_content_4e3d7f_idx')],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
    ]
