# Generated by Django 5.2.7 on 2026-02-04 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feeditem',
            name='feed_feedit_created_d2e023_idx',
        ),
        migrations.RemoveIndex(
            model_name='feeditem',
            name='feed_feedit_score_2ec6b7_idx',
        ),
        migrations.AddField(
            model_name='feeditem',
            name='liked_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have liked this content', related_name='liked_feed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['created_at'], name='feed_feedit_created_c14b92_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['likes_count'], name='feed_feedit_likes_c_5c9588_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['score'], name='feed_feedit_score_09c1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['user', 'created_at'], name='feed_feedit_user_id_2755a2_idx'),
        ),
    ]
