# Generated by Django 5.2.7 on 2026-02-20 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_feeditem_feed_feedit_created_d2e023_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='course_mode',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('surgery', 'Surgery'), ('commed', 'Community Medicine')], default='commed', help_text='Course mode of the content', max_length=20),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['course_mode'], name='feed_feedit_course__269d97_idx'),
        ),
    ]
