# Generated by Django 5.2.7 on 2026-02-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feeditem_course_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='course_mode',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('surgery', 'Surgery'), ('commed', 'Community Medicine')], max_length=20),
        ),
    ]
